2025-04-06 19:11:25,557 - INFO - _client - _client.py:1025 - HTTP Request: GET https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json "HTTP/1.1 200 OK"
2025-04-06 19:11:32,021 - INFO - testing_goldens - testing_goldens.py:135 - Loaded total of 851 Ch  unks
2025-04-06 19:11:32,801 - INFO - testing_goldens - testing_goldens.py:237 - Testing Attack @ 2025-04-06 19:11:32.801032+08:00
2025-04-06 19:12:28,962 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:12:42,869 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:12:59,408 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:15:02,627 - ERROR - RagFlow - RagFlow.py:325 - Error in model call back guardrails: HTTPSConnectionPool(host='hub.api.guardrailsai.com', port=443): Max retries exceeded with url: /validator/detect_pii/inference (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001356C432850>: Failed to resolve 'hub.api.guardrailsai.com' ([Errno 11002] getaddrinfo failed)"))
2025-04-06 19:15:02,628 - INFO - RagFlow - RagFlow.py:326 - Defense Activated, using defense reponses........
2025-04-06 19:15:15,371 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:15:35,517 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:15:35,707 - INFO - testing_goldens - testing_goldens.py:284 - Results saved in: C:\Users\yinki\OneDrive\NUS\BT4103\RAG Model\ragflow_capstone\ragflow_python\data\data_2025-04-06_19-11-31
2025-04-06 19:15:35,708 - INFO - testing_goldens - testing_goldens.py:292 - ASR via Vulnerability Scores: 0.0
2025-04-06 19:16:07,266 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:16:28,220 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:17:08,648 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:17:31,743 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:19:49,131 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:20:18,589 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:20:48,061 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:21:47,360 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:22:09,289 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:22:37,593 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:23:02,836 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:23:54,589 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:24:06,096 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 19:24:08,654 - INFO - testing_goldens - testing_goldens.py:345 - Saved to C:\Users\yinki\OneDrive\NUS\BT4103\RAG Model\ragflow_capstone\ragflow_python\data\data_2025-04-06_19-11-31
2025-04-06 19:24:08,655 - INFO - testing_goldens - testing_goldens.py:349 - Uploading to Supabase.............
2025-04-06 19:24:11,954 - INFO - _client - _client.py:1025 - HTTP Request: GET https://bggngaqkkmslamsbebew.supabase.co/rest/v1/Generation_attacks?select=attack_id&attack_id=eq.2119 "HTTP/2 404 Not Found"
2025-04-06 19:24:11,963 - WARNING - helpers - helpers.py:58 - Error generating unique id for Generation_attacks, generating randomly instead
2025-04-06 19:24:18,881 - INFO - _client - _client.py:1025 - HTTP Request: POST https://bggngaqkkmslamsbebew.supabase.co/rest/v1/Attack_Type "HTTP/2 201 Created"
2025-04-06 19:24:19,065 - INFO - _client - _client.py:1025 - HTTP Request: POST https://bggngaqkkmslamsbebew.supabase.co/rest/v1/Attack_Results "HTTP/2 201 Created"
2025-04-06 19:24:19,124 - INFO - _client - _client.py:1025 - HTTP Request: POST https://bggngaqkkmslamsbebew.supabase.co/rest/v1/Generation_Attacks?columns=%22faithfulness%22%2C%22attacked_chunks%22%2C%22contextual_recall%22%2C%22answer_relevancy%22%2C%22experiment_id%22%2C%22attack_id%22%2C%22contextual_relevancy%22%2C%22created_at%22%2C%22contextual_precision%22%2C%22attacked_question%22%2C%22attack_name%22%2C%22attacked_answer%22 "HTTP/2 201 Created"
