2025-03-09 18:18:23,298 - INFO - base_attack_script - base_attack_script.py:79 - Testing Attack @ 2025-03-09 18:18:23.298877+08:00
2025-03-09 18:19:24,986 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:19:38,103 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:19:52,857 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:20:04,607 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:20:16,209 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:20:30,636 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:20:40,135 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:20:51,119 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:21:04,602 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:21:15,815 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:21:27,883 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:21:42,076 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-03-09 18:21:42,952 - ERROR - RagFlow - RagFlow.py:234 - Error at Target Model Callback: `model_name` llama3.2:latest doesn't exist
2025-03-09 18:21:42,990 - ERROR - RagFlow - RagFlow.py:234 - Error at Target Model Callback: `model_name` llama3.2:latest doesn't exist
2025-03-09 18:21:43,022 - ERROR - RagFlow - RagFlow.py:234 - Error at Target Model Callback: `model_name` llama3.2:latest doesn't exist
