2025-04-06 11:44:55,243 - INFO - _client - _client.py:1025 - HTTP Request: GET https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json "HTTP/1.1 200 OK"
2025-04-06 11:44:56,763 - INFO - testing_goldens_mak - testing_goldens_mak.py:122 - Loaded total of 851 Chunks
2025-04-06 11:45:00,222 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:02,087 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:03,308 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:04,205 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:06,037 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:07,169 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:07,935 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:09,335 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:10,523 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:11,349 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:13,057 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:14,521 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:16,215 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:17,440 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:18,384 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:19,197 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:20,779 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:21,673 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:22,348 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:24,065 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:25,526 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:26,943 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:27,991 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:28,971 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:30,648 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:31,716 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:32,605 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:34,831 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:35,718 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:36,498 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:38,232 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:39,526 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:40,970 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:42,231 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:43,187 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:44,106 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:45,435 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:46,637 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:47,556 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:49,073 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:50,500 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:52,153 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:53,143 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:55,336 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:56,273 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:57,449 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:45:58,445 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:00,932 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:02,178 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:03,271 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:05,476 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:06,718 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:08,464 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:09,389 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:11,031 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:11,992 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:13,627 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:14,538 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:16,410 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:17,512 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:19,846 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:20,925 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:21,654 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:22,536 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:23,633 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:24,390 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:26,023 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:27,373 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:28,919 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:30,145 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:31,168 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:32,195 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:34,485 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:35,713 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:36,677 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:38,405 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:39,687 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:41,666 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:42,784 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:43,926 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:44,646 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:47,194 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:49,619 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:50,478 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:52,706 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:54,082 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:55,959 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:57,015 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:58,000 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:46:59,522 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:00,506 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:01,428 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:02,935 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:03,879 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:04,689 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:06,282 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:07,384 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:09,334 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:10,440 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:11,289 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:13,369 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:14,688 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:16,688 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:18,133 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:19,140 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:19,914 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:21,537 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:22,646 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:23,386 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:25,502 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:26,741 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:28,633 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:29,924 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:30,914 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:32,932 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:33,948 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:35,858 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:37,071 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:37,792 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:39,424 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:40,639 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:41,465 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:43,637 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:45,233 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:46,858 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:47,776 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:49,267 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:50,415 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:51,526 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:52,773 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:55,064 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:56,076 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:57,274 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:57,912 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:47:58,103 - INFO - testing_goldens_mak - testing_goldens_mak.py:222 - Testing Attack @ 2025-04-06 11:47:58.103058+08:00
2025-04-06 11:48:01,410 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:01,845 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:02,375 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:06,185 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:06,666 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:07,251 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:11,440 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:11,942 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:12,604 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:16,232 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:16,673 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:17,245 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:19,754 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:20,237 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:20,721 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:22,897 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:23,301 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:23,764 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:26,273 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:26,708 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:27,172 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:29,091 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:29,532 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:30,011 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:33,317 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:33,769 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:34,309 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:38,102 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:38,573 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:39,154 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:40,085 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:40,535 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:40,971 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:41,615 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:42,024 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:42,466 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:43,365 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:43,795 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:44,226 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:45,112 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:45,544 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:45,976 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:46,532 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:46,956 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:47,386 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:48,251 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:48,643 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:49,082 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:49,907 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:50,333 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:50,767 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:51,484 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:51,863 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:52,282 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:53,364 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:53,794 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:54,233 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:55,132 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:55,513 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:55,940 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:57,186 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:57,569 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:58,020 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:58,747 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:59,132 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:48:59,554 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:00,570 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:00,964 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:01,399 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:02,338 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:02,716 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:03,150 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:04,167 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:04,547 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:04,985 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:08,733 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:09,228 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:09,808 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:13,600 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:14,084 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:14,658 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:18,895 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:19,408 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:20,071 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:21,970 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:22,377 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:22,838 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:26,119 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:26,548 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:27,091 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:27,966 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:28,343 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:28,769 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:29,860 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:30,244 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:30,683 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:31,950 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:32,333 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:32,794 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:34,040 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:34,483 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:34,953 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:35,962 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:36,390 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:36,824 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:37,719 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:38,113 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:38,556 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:39,253 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:39,630 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:40,065 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:40,966 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:41,393 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:41,784 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:42,723 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:43,102 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:43,499 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:44,201 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:44,632 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:45,054 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:48,418 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:48,853 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:49,382 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:52,688 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:53,121 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:53,649 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:57,336 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:57,775 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:49:58,328 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:00,850 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:01,275 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:01,755 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:04,620 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:05,032 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:05,537 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:08,969 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:09,430 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:09,974 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:13,186 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:13,661 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:14,179 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:17,838 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:18,356 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:18,922 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:22,198 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:22,632 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:23,172 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:26,816 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:27,266 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:27,820 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:31,120 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:31,552 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:32,082 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:34,847 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:35,273 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:35,751 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:38,654 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:39,131 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:39,643 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:42,144 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:42,565 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:43,031 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:43,925 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:44,308 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:44,703 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:45,973 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:46,363 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:46,816 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:47,736 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:48,177 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:48,574 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:49,300 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:49,691 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:50,121 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:51,186 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:51,582 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:52,024 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:55,613 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:56,064 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:50:56,645 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:00,391 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:00,900 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:01,466 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:04,977 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:05,411 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:05,960 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:09,949 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:10,463 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:11,098 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:14,389 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:14,819 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:15,345 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:17,082 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:17,465 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:17,938 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:22,381 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:22,919 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:23,603 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:28,041 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:28,566 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:29,228 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:34,564 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:35,165 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:35,807 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:38,092 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:38,572 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:51:39,036 - INFO - _client - _client.py:1025 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
2025-04-06 11:53:25,660 - ERROR - base_events - base_events.py:1820 - _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=PromptCallableException("The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF75742F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function\nthat accepts a prompt string, **kwargs, and returns a string.\n If you're using a custom LLM callable, please see docs\n here: https://go.guardrailsai.com/B1igEy3")>
Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021BF75742F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF75742F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 32, in __call__
    result = self._invoke_llm(
             ^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\llm_providers.py", line 485, in _invoke_llm
    llm_response = self.llm_api(*args, **kwargs)  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 275, in target_model_callback_g
    datasets = self.rag_object.list_datasets(name="nomic")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(ragflow_sdk.ragflow.RAGFlow.list_datasets) at 0x21be02f9f80>", line 138, in list_datasets
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 82, in list_datasets
    res = self.get("/datasets",
          ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 38, in get
    res = requests.get(url=self.api_url + path, params=params, headers=self.authorization_header,json=json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF75742F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\deepeval\red_teaming\red_teamer.py", line 462, in _a_attack
    actual_output = await target_model_callback(attack.input)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 302, in target_model_callback_guardrails
    validated_response = self.guard(
                         ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 918, in __call__
    return trace_guard_execution(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 206, in trace_guard_execution
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 195, in trace_guard_execution
    result = _execute_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 799, in _execute
    return guard_context.run(
           ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\common.py", line 100, in wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 778, in __exec
    return self._exec(
           ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 877, in _exec
    call = runner(call_log=call_log, prompt_params=prompt_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 200, in __call__
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 170, in __call__
    iteration = self.step(
                ^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 104, in trace_step_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 96, in trace_step_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 284, in step
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 250, in step
    llm_response = self.call(messages, api, output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 308, in trace_call_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 297, in trace_call_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 430, in call
    llm_response = api_fn(messages=messages_source(messages))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 36, in __call__
    raise PromptCallableException(
guardrails.classes.llm.prompt_callable.PromptCallableException: The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF75742F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function
that accepts a prompt string, **kwargs, and returns a string.
 If you're using a custom LLM callable, please see docs
 here: https://go.guardrailsai.com/B1igEy3
2025-04-06 11:53:25,663 - ERROR - base_events - base_events.py:1820 - _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=PromptCallableException("The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF7519550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function\nthat accepts a prompt string, **kwargs, and returns a string.\n If you're using a custom LLM callable, please see docs\n here: https://go.guardrailsai.com/B1igEy3")>
Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021BF7519550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF7519550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 32, in __call__
    result = self._invoke_llm(
             ^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\llm_providers.py", line 485, in _invoke_llm
    llm_response = self.llm_api(*args, **kwargs)  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 275, in target_model_callback_g
    datasets = self.rag_object.list_datasets(name="nomic")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(ragflow_sdk.ragflow.RAGFlow.list_datasets) at 0x21be02f9f80>", line 138, in list_datasets
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 82, in list_datasets
    res = self.get("/datasets",
          ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 38, in get
    res = requests.get(url=self.api_url + path, params=params, headers=self.authorization_header,json=json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF7519550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\deepeval\red_teaming\red_teamer.py", line 462, in _a_attack
    actual_output = await target_model_callback(attack.input)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 302, in target_model_callback_guardrails
    validated_response = self.guard(
                         ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 918, in __call__
    return trace_guard_execution(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 206, in trace_guard_execution
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 195, in trace_guard_execution
    result = _execute_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 799, in _execute
    return guard_context.run(
           ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\common.py", line 100, in wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 778, in __exec
    return self._exec(
           ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 877, in _exec
    call = runner(call_log=call_log, prompt_params=prompt_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 200, in __call__
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 170, in __call__
    iteration = self.step(
                ^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 104, in trace_step_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 96, in trace_step_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 284, in step
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 250, in step
    llm_response = self.call(messages, api, output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 308, in trace_call_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 297, in trace_call_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 430, in call
    llm_response = api_fn(messages=messages_source(messages))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 36, in __call__
    raise PromptCallableException(
guardrails.classes.llm.prompt_callable.PromptCallableException: The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF7519550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function
that accepts a prompt string, **kwargs, and returns a string.
 If you're using a custom LLM callable, please see docs
 here: https://go.guardrailsai.com/B1igEy3
2025-04-06 11:53:25,669 - ERROR - base_events - base_events.py:1820 - _GatheringFuture exception was never retrieved
future: <_GatheringFuture finished exception=PromptCallableException("The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF74F6570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function\nthat accepts a prompt string, **kwargs, and returns a string.\n If you're using a custom LLM callable, please see docs\n here: https://go.guardrailsai.com/B1igEy3")>
Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000021BF74F6570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF74F6570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 32, in __call__
    result = self._invoke_llm(
             ^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\llm_providers.py", line 485, in _invoke_llm
    llm_response = self.llm_api(*args, **kwargs)  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 275, in target_model_callback_g
    datasets = self.rag_object.list_datasets(name="nomic")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(ragflow_sdk.ragflow.RAGFlow.list_datasets) at 0x21be02f9f80>", line 138, in list_datasets
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 82, in list_datasets
    res = self.get("/datasets",
          ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\ragflow_sdk\ragflow.py", line 38, in get
    res = requests.get(url=self.api_url + path, params=params, headers=self.authorization_header,json=json)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF74F6570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\tasks.py", line 314, in __step_run_and_handle_result
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\deepeval\red_teaming\red_teamer.py", line 462, in _a_attack
    actual_output = await target_model_callback(attack.input)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\BT4240\ragflow\ragflow_capstone\ragflow_python\src\RagFlow.py", line 302, in target_model_callback_guardrails
    validated_response = self.guard(
                         ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 918, in __call__
    return trace_guard_execution(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 206, in trace_guard_execution
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\guard_tracing.py", line 195, in trace_guard_execution
    result = _execute_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 799, in _execute
    return guard_context.run(
           ^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\common.py", line 100, in wrapped_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 778, in __exec
    return self._exec(
           ^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\guard.py", line 877, in _exec
    call = runner(call_log=call_log, prompt_params=prompt_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 200, in __call__
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 170, in __call__
    iteration = self.step(
                ^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 104, in trace_step_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 96, in trace_step_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 284, in step
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 250, in step
    llm_response = self.call(messages, api, output)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\hub_telemetry\hub_tracing.py", line 150, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 308, in trace_call_wrapper
    raise e
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\telemetry\runner_tracing.py", line 297, in trace_call_wrapper
    response = fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\run\runner.py", line 430, in call
    llm_response = api_fn(messages=messages_source(messages))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\inventoryScanner\.venv\ragflow_capstone\Lib\site-packages\guardrails\classes\llm\prompt_callable.py", line 36, in __call__
    raise PromptCallableException(
guardrails.classes.llm.prompt_callable.PromptCallableException: The callable `fn` passed to `Guard(fn, ...)` failed with the following error: `HTTPConnectionPool(host='localhost', port=9380): Max retries exceeded with url: /api/v1/datasets?page=1&page_size=30&orderby=create_time&desc=True&name=nomic (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021BF74F6570>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))`. Make sure that `fn` can be called as a function
that accepts a prompt string, **kwargs, and returns a string.
 If you're using a custom LLM callable, please see docs
 here: https://go.guardrailsai.com/B1igEy3
